Task 027/create entity category
DmitryJig/Financial_management_app pull request #24
Opened 2023-06-05 18:39 UTC by DmitryJig

2023-06-05 20:22 UTC, Konstantin8881888 reviewed
Файл 5-create-report-table.yaml пересекается с файлом транзакций таблиц по названию (и там и там цифра 5 в начале). В принципе, фигня, но не красиво выглядит. 
Плюс не мешало бы добавить файл/файлы на вставку в таблицу тестовой записи (в папке resouces/db/changelog/data), либо изменить уже существующий там файл.
И ещё, очень желательно, пока не забыли, добавить в файл сущности Profile коллекцию категории. Кстати, у тебя на старой версии девелопмента основан код. Проблем конфликтации, вроде, не видно, но лучше бы на основе обновлённой сделать.

2023-06-06 21:32 UTC, kilyaser requested changes

2023-06-06 21:32 UTC, kilyaser commented on src/main/java/com/finance/app/entity/Category.java
> +    private Collection<Transaction> transactions;
Я думаю правильно поставить связь @OneToMany

2023-06-06 21:32 UTC, kilyaser commented on src/main/java/com/finance/app/entity/Report.java
> +    @Column(name = "expense_by_category")
Здесь нужно подумать как сохранять эти данные в БД  это ведь Map и нужно ли, может имеет смысл их динамически формировать без сохранения.

2023-06-07 18:32 UTC, kilyaser approved these changes

2023-06-07 18:33 UTC, merged